
export const CLUSTER_COLORS = [
  "#3B82F6", "#6366F1", "#8B5CF6", "#EC4899", "#F43F5E",
  "#F97316", "#EAB308", "#84CC16", "#10B981", "#06B6D4",
  "#0EA5E9", "#475569", "#78716C", "#94A3B8", "#64748B"
];

export const STATUS_COLOR_MAP: Record<string, string> = {
  'TO_ASK': '#3b82f6',
  'ASKED': '#10b981',
  'NON_ASKED': '#94a3b8',
  'DONE': '#6366f1',
  'REFUSED': '#ef4444',
  'TELESCOPED': '#f59e0b'
};

export const COMMUNE_STATUSES = [
  { id: 'ASKED', label: 'Demandé', color: '#10b981' },
  { id: 'NON_ASKED', label: 'Non demandé', color: '#94a3b8' },
  { id: 'REFUSED', label: 'Refusé', color: '#ef4444' },
  { id: 'DONE', label: 'Déjà faite', color: '#6366f1' },
  { id: 'TELESCOPED', label: 'Téléscopé', color: '#f59e0b' }
];

export const TARGET_POPULATION = 8000;
export const DEPT_CODE = '25';

export const DEFAULT_MAX_POP_FILTER = 200000;

export const MIN_1W = 7500;
export const MAX_1W = 12500;

export const MIN_2W = 14000;
export const MAX_2W = 18000;

export const MIN_3W = 21000;
export const MAX_3W = 70000;

export const API_GEO_URL = 'https://geo.api.gouv.fr/departements/25/communes?geometry=contour&format=geojson&type=commune-actuelle';

export const TARGET_COMMUNES_LIST = [
  "CHAPELLE-DES-BOIS", "CHAUX-NEUVE", "MOUTHE", "LES VILLEDIEU", "GELLIN", "RONDEFONTAINE", "ROCHEJEAN",
  "BREY-ET-MAISON-DU-BOIS", "REMORAY-BOUJEONS", "LONGEVILLES-MONT-D'OR", "FOURCATIER-ET-MAISON-NEUVE",
  "LABERGEMENT-SAINTE-MARIE", "VAUX-ET-CHANTEGRUE", "METABIEF", "SAINT-ANTOINE", "MALBUISSON", "SAINT-POINT-LAC",
  "MALPAS", "LES GRANGETTES", "INDEVILLERS", "CHARMAUVILLERS", "DAMPRICHARD", "MAICHE", "CERNAY-L'EGLISE",
  "LES BRESEUX", "THIEBOUHANS", "MONTANDON", "TREVILLERS", "LES PLAINS-ET-GRANDS-ESSARTS", "COURTEFONTAINE",
  "VERRIERES-DE-JOUX", "LA CLUSE-ET-MIJOUX", "OYE-ET-PALLET", "LES FOURGS", "MONTPERREUX", "LES HOPITAUX-VIEUX",
  "TOUILLON-ET-LOUTELET", "LES HOPITAUX-NEUFS", "JOUGNE", "VILLERS-SOUS-CHALAMONT", "BOUJAILLES", "COURVIERES",
  "FRASNE", "BONNEVAUX", "BOUVERANS", "LA PLANEE", "DOMPIERRE-LES-TILLEULS", "LA RIVIERE-DRUGEON", "SAINTE-COLOMBE",
  "GRANGES-NARBOZ", "CHAPELLE-D'HUIN", "BULLE", "BANNANS", "CHAFFOIS", "BELLEHERBE", "CHARMOILLE", "BRETONVILLERS",
  "PLAIMBOIS-DU-MIROIR", "FOURNET-BLANCHEROCHE", "LE RUSSEY", "BONNETAGE", "LES FONTENELLES", "FRAMBOUHANS",
  "LES ECORCES", "CHARQUEMONT", "PONTARLIER", "HOUTAUD", "DOMMARTIN", "DOUBS", "SOMBACOUR", "VUILLECIN",
  "BIANS-LES-USIERS", "ARCON", "GOUX-LES-USIERS", "MAISONS-DU-BOIS-LIEVREMONT", "OUHANS", "BUGNY", "SAINT-GORGON-MAIN",
  "VALONNE", "DAMBELIN", "VILLARS-SOUS-DAMPJOUX", "NOIREFONTAINE", "MONTECHEROUX", "CHAMESOL", "VILLARS-LES-BLAMONT",
  "PIERREFONTAINE-LES-BLAMONT", "AUTECHAUX-ROIDE", "BLAMONT", "GLAY", "ROCHES-LES-BLAMONT", "ECURCEY", "BOURGUIGNON",
  "VILLARS-SOUS-ECOT", "ECOT", "MATHAY", "BONDEVAL", "MESLIERES", "ABBEVILLERS", "LA CHAUX", "ARC-SOUS-CICON",
  "GILLEY", "PASSONFONTAINE", "FOURNETS-LUISANS", "ORCHAMPS-VENNES", "FLANGEBOUCHE", "AVOUDREY", "LORAY", "VENNES",
  "APPENANS", "SAINT-MAURICE-COLOMBIER", "LONGEVELLE-SUR-DOUBS", "ETOUVANS", "LOUGRES", "DAMPIERRE-SUR-LE-DOUBS",
  "BERCHE", "BAVANS", "MONTBENOIT", "VILLE-DU-PONT", "LES GRAS", "LA LONGEVILLE", "GRAND'COMBE-CHATELEU",
  "LES COMBES", "MONTLEBON", "LES FINS", "MORTEAU", "EVILLERS", "MOUTHIER-HAUTE-PIERRE", "ORNANS", "LES-PREMIERS-SAPINS",
  "SAULES", "GUYANS-DURNES", "ETALANS", "FALLERANS", "ETRAY", "EPENOY", "VALDAHON", "VERCEL-VILLEDIEU-LE-CAMP",
  "ONANS", "MONTENOIS", "ARCEY", "SAINTE-MARIE", "PRESENTEVILLERS", "DUNG", "ALLONDANS", "ISSANS", "DESANDANS",
  "SEMONDANS", "RAYNANS", "AIBRE", "LAIRE", "VILLERS-LE-LAC", "LE BARBOUX", "LA CHENALOTTE", "NOEL-CERNEUX",
  "LE BIZOT", "LE BELIEU", "LE LUHIER", "FUANS", "GUYANS-VENNES", "BART", "COURCELLES-LES-MONTBELIARD",
  "VOUJEAUCOURT", "ARBOUANS", "CHAMPLIVE", "OSSE", "VAIRE", "GENNES", "NANCRAY", "BOUCLANS", "GONSANS",
  "NAISEY-LES-GRANGES", "L'HOPITAL-DU-GROSBOIS", "TREPOT", "MAMIROLLE", "LA CHEVILLOTTE", "MONTROND-LE-CHATEAU",
  "TARCENAY-FOUCHERANS", "LES-MONTS-RONDS", "FONTAIN", "LA VEZE", "SAONE", "MORRE", "VIEUX-CHARMONT", "EXINCOURT",
  "TAILLECOURT", "MONTFAUCON", "CHALEZEULE", "CHALEZE", "ROCHE-LEZ-BEAUPRE", "THISE", "AMAGNEY", "MARCHAUX-CHAUDEfontaine",
  "VIEILLEY", "VENISE", "ROULANS", "VENNANS", "POULIGNEY-LUANS", "MONCEY", "RIGNEY", "LA TOUR-DE-SCAY", "FOURG",
  "VILLARS-SAINT-GEORGES", "CESSEY", "ABBANS-DESSUS", "ABBANS-DESSOUS", "ROSET-FLUANS", "OSSELLE-ROUTELLE",
  "BOUSSIERES", "VORGES-LES-PINS", "TORPES", "SAINT-VIT", "THORAISE", "RANCENAY", "DAMPIERRE-LES-BOIS", "BADEVEL",
  "DASLE", "VANDONCOURT", "SELONCOURT", "BONNAY", "DEVECEY", "TALLENAY", "CHATILLON-LE-DUC", "ECOLE-VALENTIN",
  "PIREY", "ALLENJOIE", "ETUPES", "DAMBENOIS", "BROGNARD", "NOMMAY", "GRANDFONTAINE", "AVANne-AVENEY", "LARNOD",
  "BUSY", "CHARNAY", "RUREY", "EPEUGNEY", "PUGEY", "CHENECEY-BUILLON", "CUSSEY-SUR-L'OGNON", "GENEUILLE",
  "LES AUXONS", "MISEREY-SALINES", "MONCLEY", "CHAUCENNE", "FRANOIS", "SERRE-LES-SAPINS", "CHAMPAGNEY",
  "CHAMPVANS-LES-MOULINS", "POUILLEY-LES-VIGNES", "PELOUSEY", "CHEVIGNEY-SUR-L'OGNON", "RUFFEY-LE-CHATEAU",
  "RECOLOGNE", "NOIRONTE", "AUDEUX", "MAZEROLLES-LE-SALIN", "LAVERNAY", "FRANEY", "BURGILLE", "VILLERS-BUZON",
  "CHEMAUDIN-ET-VAUX", "DANNEMARIE-SUR-CRETE", "POUILLEY-FRANCAIS", "FERRIERES-LES-BOIS", "LANTENNE-VERTIERE",
  "MERCEY-LE-GRAND", "BERTHELANGE", "BATTENANS-LES-MINES", "AUTECHAUX", "BAUME-LES-DAMES"
];
