import React, { useState, useEffect, useRef } from 'react';
import { ChevronDown } from 'lucide-react';

export const WeekRatioSelector: React.FC<{ rank: number; total: number; onUpdateTotal: (d: number) => void; }> = ({ rank, total, onUpdateTotal }) => {
    const [isOpen, setIsOpen] = useState(false); const dropdownRef = useRef<HTMLDivElement>(null);
    useEffect(() => { const handleClickOutside = (event: MouseEvent) => { if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) { setIsOpen(false); } }; document.addEventListener("mousedown", handleClickOutside); return () => document.removeEventListener("mousedown", handleClickOutside); }, []);
    return ( <div className="relative text-xs font-semibold text-[var(--text-secondary)] flex items-center gap-1 bg-white/50 dark:bg-[var(--bg-card-solid)]/50 px-2 py-1 rounded-lg border border-[var(--border-subtle)]" ref={dropdownRef}> <span>Semaine {rank} sur</span> <div className="text-red-600 font-bold cursor-pointer hover:bg-red-50 px-1 rounded transition-colors select-none flex items-center" onClick={(e) => { e.stopPropagation(); setIsOpen(!isOpen); }}> {total} </div> {isOpen && ( <div className="absolute top-full right-0 mt-1 bg-white dark:bg-[var(--bg-card-solid)] border border-[var(--border-subtle)] shadow-xl rounded-lg overflow-hidden z-50 flex flex-col min-w-[40px]"> {[1, 2, 3, 4, 5].map(n => ( <div key={n} onClick={(e) => { e.stopPropagation(); onUpdateTotal(n); setIsOpen(false); }} className={`px-3 py-2 text-center cursor-pointer hover:bg-slate-50 dark:hover:bg-slate-700/50 font-bold text-xs border-b border-slate-50 last:border-0 ${total === n ? 'text-red-600 bg-red-50' : 'text-[var(--text-secondary)]'}`} > {n} </div> ))} </div> )} </div> );
};

export const ZoneTimeManager: React.FC<{ startWeek: number; duration: number; onUpdateStart: (w: number) => void; onUpdateDuration: (d: number) => void; currentWeek: number; }> = ({ startWeek, duration, onUpdateStart, onUpdateDuration, currentWeek }) => {
    const [isStartOpen, setIsStartOpen] = useState(false); const currentRank = Math.max(1, currentWeek - startWeek + 1);
    return ( <div className="flex items-center gap-2 bg-slate-100 dark:bg-slate-800 p-1.5 rounded-lg border border-[var(--border-subtle)] ml-4"> <div className="relative"> <button onClick={() => setIsStartOpen(!isStartOpen)} className="flex items-center gap-1 px-2 py-1 bg-white dark:bg-[var(--bg-card-solid)] border border-[var(--border-subtle)] rounded hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-colors text-xs font-bold text-[var(--text-primary)]"> Start S{startWeek} <ChevronDown size={10} className="text-[var(--text-muted)]"/> </button> {isStartOpen && ( <div className="absolute top-full left-0 mt-1 bg-white dark:bg-[var(--bg-card-solid)] border border-[var(--border-subtle)] shadow-xl rounded-lg overflow-y-auto max-h-[200px] z-50 w-20"> {Array.from({length: 52}, (_, i) => i + 1).map(w => ( <div key={w} className={`px-3 py-2 text-xs cursor-pointer hover:bg-slate-50 dark:hover:bg-slate-700/50 ${w === startWeek ? 'bg-orange-50 text-orange-600 font-bold' : 'text-[var(--text-secondary)]'}`} onClick={() => { onUpdateStart(w); setIsStartOpen(false); }} > S{w} </div> ))} </div> )} </div> <span className="text-slate-300">|</span> <WeekRatioSelector rank={currentRank} total={duration} onUpdateTotal={onUpdateDuration} /> </div> );
};
